# Generated by Django 2.1 on 2018-08-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='django', max_length=255),
        ),
    ]
